### PR TITLE
upgrade go-redis to v8 and ccache to v3

### PR DESCRIPTION
**Pull request by rts-gordon**
Hi @Pacific73 
 I have upgraded go-redis to v9 and ccache to v3, they are the latest versions.

 I tested the latest version code, save data to Redis and Memory, all passed.

  Can you please take a look at this PR, thank you.

 PS1:  repo "https://github.com/go-redis/redis" has relocate to "https://github.com/redis/go-redis"
 PS2:  repo "https://github.com/karlseguin/ccache/v3" uses the generic declaration

### CODE REVIEW

**Comment by asjdf** [comment]
Hi,
I made a copy and added more features (including using the latest dependence.) and I hope this repo helps you.
https://github.com/asjdf/gorm-cache

**Comment by rts-gordon** [comment]
> Hi, I made a copy and added more features (including using the latest dependence.) and I hope this repo helps you. https://github.com/asjdf/gorm-cache

Is there a plan to support multi tenant？ https://github.com/Pacific73/gorm-cache/issues/22

**Comment by asjdf** [comment]
> > Hi, I made a copy and added more features (including using the latest dependence.) and I hope this repo helps you. https://github.com/asjdf/gorm-cache
> 
> 
> 
> Is there a plan to support multi tenant？ https://github.com/Pacific73/gorm-cache/issues/22

In fact, the multi-tenant example you mentioned, I think is mainly due to the library's poor primary key cache logic, which I would like to optimize in my repo. I also hope that my experiment will help this repo.

**Comment by rts-gordon** [comment]
> 

Yes, agree with you. If the client can define the Redis cache KEY themselves, we can implement the multi tenant, may be more features.

**Pull request closed without merging**
